### ISSUE TITLE
[NEW] ingest data via naver api - news

### ISSUE THREAD

**Issue by seoyeong200** [brickstudy/ETL#5]
### 요청 내용

네이버 API를 활용하여 검색(뉴스) 여행 키워드 수집

- [x] 1/ 네이버 개발자 계정 생성 
https://developers.naver.com/main/
- [x] 2/ 일일 토큰량 확인
25000 requests per a day
- [x] 3/ 네이버 API 데이터 수집 확인(test)
    - [ ] 수집로직부터 먼저 작성
    - [ ] modularize, logging, token/configuration management
- [x] 4/ 일일 토큰 최대량 Dag 파일 작성(test)
- [x] 5/ Airflow 공용 인프라 배포

## 요건 파악

1. 데이터 수집 스크립트 코드는 https://github.com/brickstudy/ETL 하에 새로운 경로를 생성하고 작업하면 될까요?

2. https://github.com/brickstudy/ETL/tree/main/dags 하에 dag 파일 작성하면 될까요?

3. 데이터 적재되는 downstream 어디일까요? (s3 bucket uri?)

4. 현재 airflow 실행 환경을 제대로 이해하지 못해서 궁금한데, 한번 미팅 시간 잡아서 공유해주시면 좋겠습니다!

5. 여행 단일 키워드로 25000건 request 다 쓰는지?
- 유사어 등 다양한 키워드로 쿼리하면 더 다양하게 수집될 수 있지 않을까 하는 생각
- 테스트해보진 않았지만 display(한번에 표시될 검색 결과 개수) 최댓값이 100-> 일일 2,500,000개 뉴스 수집될 수 있을텐데, 데이터 중복 수집이 많이 일어나지 않을까? 생각

<br>

## 정리

<br>

## 🔗 관련 링크

- [naver openapi reference](https://developers.naver.com/docs/serviceapi/search/news/news.md#%EB%89%B4%EC%8A%A4)

<br>

## 📌 진행상황

> *진행상황에 예상 마감 일정까지 함께 기재해주세요!!

- [ ] 요건파악(~기간)
- [ ] 내용

@robert-min

**Comment by robert-min** [comment]
### TO DO list
- [ ] dag, etl 경로 결정
- [ ] branch명 규칙 결정
- [ ] ETL repo 안에서 spark docker-compose 위치 결정

------------ PR

- [ ] 서영님 프로젝트(news)

---------

1/ dag, module 어떻게 관리 경로(어떤 경로 - 리서치)
- 고민이 필요하다
- 깔끔한게(프로덕트, test 경로 분리)
1. 프로덕트 코드(airflow) > dag
2. spark 

dag/naverapi-news/xxx_dag.py
dag/naverapi-news/spark/module1.py
dag/common/module2.py

test/naverapi-news/spark 작업을

./src/실제사용할 코드

./test/ -> pytest, unitest



----------------

2/ branch 명 규칙
- 관리 목적
- 계정 : 여행, 주식 주제가 !

ex)
s3 경로 : s3://brickstudy/travel/bronze/naverAPI/news/

신규 로직 : feature/travel_bronze_naverAPI_news
수정 로직 : fix/travel_bronze_naverAPI_news
(수정-수정 계속 쌓였을 때, 어떻게 관리할 것인가?)
> 롤백 브런치로 만들자(민준)
> 더 좋은 방법을 고민해 봐라!!(서영)
> 다른 곳 어떻게 하는지?
> 좋은 방법이 필요하다!!!!

----------------

3/ ELT github
- clone - fork ...
- spark test
- docker-compose.yaml 어떻게할지(1번 어떻게할지 정하고 가장 상위 폴더에 docker-compose 해놓기!!)
- 다른 사람이 작업하기 전에 PR(정한 규칙 기준으로!!) => 평일 중에 

----------------

4/ s3 경로

s3://brickstudy/travel/bronze/naverAPI/news/

----------------

5/ airflow는 주말에 날잡고 설명

기본
./dag: docker안 dag
./etl: docker etl

> 확인하기!!

컨테이너 안에 있으니 라이브러리 절대 경로 airflow 모듈(옛날 본거다!!)
어느 경로 확인



----------------

6/ 토큰 최대라
- 본인이 지정한 토큰만큼 수집 + 키워드
- airflow 실행할 수 있는 => 모듈(공통된 부분)

**Comment by seoyeong200** [comment]
### history
* 개발하면서 고민되는 부분 관련 히스토리입니다.(계속 업데이트)
* 민준님 데스크탑 장비 airflow장비라고 칭하겠습니다.
---
- spark etl 코드 개발) 각 개인 infra-docs 레포 clone해가서 spark 컨테이너 띄워서 작업
- 실제 spark production(data write) - databricks?
    - ETL 레포에 etl script 랑 dag script 개발 -> merged main -> airflow장비 triggered  -> airflow job 실행 -> databricks(spark) 실행(?)
    - databricks 플랫폼 상에서 실행되는거면 databricks에 ETL git repository 에서 코드 갖고와서 실행되는?
        - databricks, airflow 조사부터 필요할듯
        - [databricks+airflow guide](https://www.astronomer.io/docs/learn/use-case-airflow-databricks)
- etl script test 자체는 testcode 작성해서 검증

- ETL 프로젝트 목적
   - 저희 특징이 프로젝트가 여러 개 존재할 수 있는데, 각 프로젝트에 필요한 데이터 ingestion pipeline code가 이 ETL 프로젝트 안에 다 존재하는 것으로 이해하고 있는데, 맞는지 확인
   - 프로젝트 경로가 복잡해질듯, 그래서 브랜치, 경로 naming convention 잘 정의하라고 하신건가?

**Comment by robert-min** [comment]
@seoyeong200 
1/ databricks에서 실행
- 이 부분은 databricks 쪽 우리가 직접 사용해보면서 하나씩 확인해야할 거 같아요!!
- databricks 코드도 결국 코드는 github로 관리가되어야할텐데, 어떻게 연동되고 관리가 되면 좋을지는 좀 더 고민이 필요할거 같음!!
- databricks는 빠르면 이번 달 중순부터 사용해볼 예정!!

2/ ETL 프로젝트 여러개 일 때, 경로 복잡
- 일단은 위에 작성한대로 ETL 프로젝트 안에 다 존재하는 형태입니다.(프로젝트 별로 repo를 나누기에는 코드 동기화 문제 때문에 추가적인 솔루션이 필요하기 때문 ㅠ)
- 그래서 naming convention을 잘 고민할 필요가 있습니다!!
